DROP TABLE AUTA CASCADE CONSTRAINTS;
DROP TABLE WLASCICIELE2 CASCADE CONSTRAINTS;
DROP TABLE SAMOCHODY2 CASCADE CONSTRAINTS;
DROP TABLE PRZEDMIOTY CASCADE CONSTRAINTS;
DROP TABLE PISARZE CASCADE CONSTRAINTS;
DROP TABLE KSIAZKI CASCADE CONSTRAINTS;

-- Drop views
DROP VIEW ZESPOLY_V;
DROP VIEW PRACOWNICY_V;
DROP VIEW PISARZE_WIDOK;
DROP VIEW KSIAZKI_WIDOK;

-- Drop object types (in dependency order, children first)
DROP TYPE auto_osobowe FORCE;
DROP TYPE auto_ciezarowe FORCE;
DROP TYPE auto FORCE;

DROP TYPE Samochod2 FORCE;
DROP TYPE Wlasciciel2 FORCE;

DROP TYPE PRACOWNIK FORCE;
DROP TYPE ZESPOL FORCE;
DROP TYPE PRZEDMIOTY_TAB FORCE;

DROP TYPE ksiazka FORCE;
DROP TYPE pisarz FORCE;
DROP TYPE ksiazki_tab FORCE;

-- And so on for all other custom types
/

-- Tables
CREATE TABLE ZESPOLY
(
    ID_ZESP NUMBER(4) CONSTRAINT PK_ZESP PRIMARY KEY,
    NAZWA VARCHAR2(20),
    ADRES VARCHAR2(20)
);

CREATE TABLE ETATY
(
    NAZWA VARCHAR2(10) CONSTRAINT PK_ETAT PRIMARY KEY,
    PLACA_MIN NUMBER(6,2),
    PLACA_MAX NUMBER(6,2)
);

CREATE TABLE PRACOWNICY
(
    ID_PRAC NUMBER(6) CONSTRAINT PK_PRAC PRIMARY KEY,
    NAZWISKO VARCHAR2(15),
    ETAT VARCHAR2(10) CONSTRAINT FK_ETAT REFERENCES ETATY(NAZWA),
    ID_SZEFA NUMBER(6) CONSTRAINT FK_ID_SZEFA REFERENCES PRACOWNICY(ID_PRAC),
    ZATRUDNIONY DATE,
    PLACA_POD NUMBER(6,2) CONSTRAINT MIN_PLACA_POD CHECK(PLACA_POD>100),
    PLACA_DOD NUMBER(6,2),
    ID_ZESP NUMBER(4) CONSTRAINT FK_ID_ZESP REFERENCES ZESPOLY(ID_ZESP)
);

-- Inserts for ZESPOLY, ETATY, PRACOWNICY
INSERT INTO ZESPOLY VALUES (10,'ADMINISTRACJA','PIOTROWO 3A');
INSERT INTO ZESPOLY VALUES (20,'SYSTEMY ROZPROSZONE','PIOTROWO 3A');
INSERT INTO ZESPOLY VALUES (30,'SYSTEMY EKSPERCKIE','STRZELECKA 14');
INSERT INTO ZESPOLY VALUES (40,'ALGORYTMY','WLODKOWICA 16');
INSERT INTO ZESPOLY VALUES (50,'BADANIA OPERACYJNE','MIELZYNSKIEGO 30');

INSERT INTO ETATY VALUES ('PROFESOR',800.00,1500.00);
INSERT INTO ETATY VALUES ('ADIUNKT',510.00,750.00);
INSERT INTO ETATY VALUES ('ASYSTENT',300.00,500.00);
INSERT INTO ETATY VALUES ('STAZYSTA',150.00,250.00);
INSERT INTO ETATY VALUES ('SEKRETARKA',270.00,450.00);
INSERT INTO ETATY VALUES ('DYREKTOR',1280.00,2100.00);

INSERT INTO PRACOWNICY VALUES (100,'WEGLARZ','DYREKTOR',NULL,TO_DATE('01-01-1968','DD-MM-YYYY'),1730.00,420.50,10);
INSERT INTO PRACOWNICY VALUES (110,'BLAZEWICZ','PROFESOR',100,TO_DATE('01-05-1973','DD-MM-YYYY'),1350.00,210.00,40);
INSERT INTO PRACOWNICY VALUES (120,'SLOWINSKI','PROFESOR',100,TO_DATE('01-09-1977','DD-MM-YYYY'),1070.00,NULL,30);
INSERT INTO PRACOWNICY VALUES (130,'BRZEZINSKI','PROFESOR',100,TO_DATE('01-07-1968','DD-MM-YYYY'),960.00,NULL,20);
INSERT INTO PRACOWNICY VALUES (140,'MORZY','PROFESOR',130,TO_DATE('15-09-1975','DD-MM-YYYY'),830.00,105.00,20);
INSERT INTO PRACOWNICY VALUES (150,'KROLIKOWSKI','ADIUNKT',130,TO_DATE('01-09-1977','DD-MM-YYYY'),645.50,NULL,20);
INSERT INTO PRACOWNICY VALUES (160,'KOSZLAJDA','ADIUNKT',130,TO_DATE('01-03-1985','DD-MM-YYYY'),590.00,NULL,20);
INSERT INTO PRACOWNICY VALUES (170,'JEZIERSKI','ASYSTENT',130,TO_DATE('01-10-1992','DD-MM-YYYY'),439.70,80.50,20);
INSERT INTO PRACOWNICY VALUES (180,'MAREK','SEKRETARKA',100,TO_DATE('20-02-1985','DD-MM-YYYY'),410.20,NULL,10);
INSERT INTO PRACOWNICY VALUES (190,'MATYSIAK','ASYSTENT',140,TO_DATE('01-09-1993','DD-MM-YYYY'),371.00,NULL,20);
INSERT INTO PRACOWNICY VALUES (200,'ZAKRZEWICZ','STAZYSTA',140,TO_DATE('15-07-1994','DD-MM-YYYY'),208.00,NULL,30);
INSERT INTO PRACOWNICY VALUES (210,'BIALY','STAZYSTA',130,TO_DATE('15-10-1993','DD-MM-YYYY'),250.00,170.60,30);
INSERT INTO PRACOWNICY VALUES (220,'KONOPKA','ASYSTENT',110,TO_DATE('01-10-1993','DD-MM-YYYY'),480.00,NULL,20);
INSERT INTO PRACOWNICY VALUES (230,'HAPKE','ASYSTENT',120,TO_DATE('01-09-1992','DD-MM-YYYY'),480.00,90.00,30);

COMMIT;

-- Types and Object tables
CREATE OR REPLACE TYPE Samochod AS OBJECT (
    marka VARCHAR2(20),
    model VARCHAR2(20),
    kilometry NUMBER,
    data_produ DATE,
    cena NUMBER(10,2)
);
/

CREATE TABLE samochody OF Samochod;

INSERT INTO samochody VALUES (Samochod('fiat','brava',60000,DATE '1999-11-30',25000));
INSERT INTO samochody VALUES (Samochod('ford','mondeo',80000,DATE '1997-05-10',45000));
INSERT INTO samochody VALUES (Samochod('mazda','323',12000,DATE '2000-09-22',52000));

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRACOWNICY CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ZESPOLY CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ETATY CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE WLASCICIELE CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE SAMOCHODY CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE TABLE ZESPOLY
(
    ID_ZESP NUMBER(4) CONSTRAINT PK_ZESP PRIMARY KEY,
    NAZWA VARCHAR2(20),
    ADRES VARCHAR2(20)
);

CREATE TABLE ETATY
(
    NAZWA VARCHAR2(10) CONSTRAINT PK_ETAT PRIMARY KEY,
    PLACA_MIN NUMBER(6,2),
    PLACA_MAX NUMBER(6,2)
);

CREATE TABLE PRACOWNICY
(
    ID_PRAC NUMBER(6) CONSTRAINT PK_PRAC PRIMARY KEY,
    NAZWISKO VARCHAR2(15),
    ETAT VARCHAR2(10) CONSTRAINT FK_ETAT REFERENCES ETATY(NAZWA),
    ID_SZEFA NUMBER(6) CONSTRAINT FK_ID_SZEFA REFERENCES PRACOWNICY(ID_PRAC),
    ZATRUDNIONY DATE,
    PLACA_POD NUMBER(6,2) CONSTRAINT MIN_PLACA_POD CHECK(PLACA_POD>100),
    PLACA_DOD NUMBER(6,2),
    ID_ZESP NUMBER(4) CONSTRAINT FK_ID_ZESP REFERENCES ZESPOLY(ID_ZESP)
);

-- ================================
-- INSERT DATA
-- ================================
INSERT INTO ZESPOLY VALUES (10,'ADMINISTRACJA','PIOTROWO 3A');
INSERT INTO ZESPOLY VALUES (20,'SYSTEMY ROZPROSZONE','PIOTROWO 3A');
INSERT INTO ZESPOLY VALUES (30,'SYSTEMY EKSPERCKIE','STRZELECKA 14');
INSERT INTO ZESPOLY VALUES (40,'ALGORYTMY','WLODKOWICA 16');
INSERT INTO ZESPOLY VALUES (50,'BADANIA OPERACYJNE','MIELZYNSKIEGO 30');

INSERT INTO ETATY VALUES ('PROFESOR',800.00,1500.00);
INSERT INTO ETATY VALUES ('ADIUNKT',510.00,750.00);
INSERT INTO ETATY VALUES ('ASYSTENT',300.00,500.00);
INSERT INTO ETATY VALUES ('STAZYSTA',150.00,250.00);
INSERT INTO ETATY VALUES ('SEKRETARKA',270.00,450.00);
INSERT INTO ETATY VALUES ('DYREKTOR',1280.00,2100.00);

INSERT INTO PRACOWNICY VALUES (100,'WEGLARZ','DYREKTOR',NULL,TO_DATE('01-01-1968','DD-MM-YYYY'),1730.00,420.50,10);
INSERT INTO PRACOWNICY VALUES (110,'BLAZEWICZ','PROFESOR',100,TO_DATE('01-05-1973','DD-MM-YYYY'),1350.00,210.00,40);
INSERT INTO PRACOWNICY VALUES (120,'SLOWINSKI','PROFESOR',100,TO_DATE('01-09-1977','DD-MM-YYYY'),1070.00,NULL,30);
INSERT INTO PRACOWNICY VALUES (130,'BRZEZINSKI','PROFESOR',100,TO_DATE('01-07-1968','DD-MM-YYYY'),960.00,NULL,20);
INSERT INTO PRACOWNICY VALUES (140,'MORZY','PROFESOR',130,TO_DATE('15-09-1975','DD-MM-YYYY'),830.00,105.00,20);
INSERT INTO PRACOWNICY VALUES (150,'KROLIKOWSKI','ADIUNKT',130,TO_DATE('01-09-1977','DD-MM-YYYY'),645.50,NULL,20);
INSERT INTO PRACOWNICY VALUES (160,'KOSZLAJDA','ADIUNKT',130,TO_DATE('01-03-1985','DD-MM-YYYY'),590.00,NULL,20);
INSERT INTO PRACOWNICY VALUES (170,'JEZIERSKI','ASYSTENT',130,TO_DATE('01-10-1992','DD-MM-YYYY'),439.70,80.50,20);
INSERT INTO PRACOWNICY VALUES (180,'MAREK','SEKRETARKA',100,TO_DATE('20-02-1985','DD-MM-YYYY'),410.20,NULL,10);
INSERT INTO PRACOWNICY VALUES (190,'MATYSIAK','ASYSTENT',140,TO_DATE('01-09-1993','DD-MM-YYYY'),371.00,NULL,20);
INSERT INTO PRACOWNICY VALUES (200,'ZAKRZEWICZ','STAZYSTA',140,TO_DATE('15-07-1994','DD-MM-YYYY'),208.00,NULL,30);
INSERT INTO PRACOWNICY VALUES (210,'BIALY','STAZYSTA',130,TO_DATE('15-10-1993','DD-MM-YYYY'),250.00,170.60,30);
INSERT INTO PRACOWNICY VALUES (220,'KONOPKA','ASYSTENT',110,TO_DATE('01-10-1993','DD-MM-YYYY'),480.00,NULL,20);
INSERT INTO PRACOWNICY VALUES (230,'HAPKE','ASYSTENT',120,TO_DATE('01-09-1992','DD-MM-YYYY'),480.00,90.00,30);

COMMIT;

-- Zad 1
CREATE OR REPLACE TYPE Samochod AS OBJECT (
    marka VARCHAR2(20),
    model VARCHAR2(20),
    kilometry NUMBER,
    data_produ DATE,
    cena NUMBER(10,2)
);
/

CREATE TABLE samochody OF Samochod;

INSERT INTO samochody VALUES (Samochod('fiat','brava',60000,DATE '1999-11-30',25000));
INSERT INTO samochody VALUES (Samochod('ford','mondeo',80000,DATE '1997-05-10',45000));
INSERT INTO samochody VALUES (Samochod('mazda','323',12000,DATE '2000-09-22',52000));

-- Zad 2
CREATE OR REPLACE TYPE Wlasciciel AS OBJECT (
    imie VARCHAR2(100),
    nazwisko VARCHAR2(100),
    auto Samochod
);
/

CREATE TABLE wlasciciele OF Wlasciciel;

INSERT INTO wlasciciele VALUES (Wlasciciel('Jan','Kowalski',Samochod('fiat','seicento',30000,DATE '2010-12-02',19500)));
INSERT INTO wlasciciele VALUES (Wlasciciel('Adam','Nowak',Samochod('opel','astra',34000,DATE '2009-06-01',33700)));

-- Zad 3
ALTER TYPE Samochod ADD MEMBER FUNCTION wartosc RETURN NUMBER;
/

CREATE OR REPLACE TYPE BODY Samochod AS
    MEMBER FUNCTION wartosc RETURN NUMBER IS
    BEGIN
        RETURN ROUND(cena * POWER(0.9, EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM data_produ)),2);
    END wartosc;
END;
/

-- Zad 4
ALTER TYPE Samochod ADD MAP MEMBER FUNCTION odwzoruj RETURN NUMBER CASCADE INCLUDING TABLE DATA;
/

CREATE OR REPLACE TYPE BODY Samochod AS
    MEMBER FUNCTION wartosc RETURN NUMBER IS
    BEGIN
        RETURN ROUND(cena * POWER(0.9, EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM data_produ)),2);
    END wartosc;

    MAP MEMBER FUNCTION odwzoruj RETURN NUMBER IS
    BEGIN
        RETURN ROUND(EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM data_produ) + (kilometry/10000),2);
    END odwzoruj;
END;
/

-- Zad 5
CREATE OR REPLACE TYPE Wlasciciel2 AS OBJECT (
    imie VARCHAR2(100),
    nazwisko VARCHAR2(100)
);
/

CREATE TABLE wlasciciele2 OF Wlasciciel2;

INSERT INTO wlasciciele2 VALUES (Wlasciciel2('Jan','Kowalski'));

CREATE OR REPLACE TYPE Samochod2 AS OBJECT (
    marka VARCHAR2(20),
    model VARCHAR2(20),
    kilometry NUMBER,
    data_produ DATE,
    cena NUMBER(10,2),
    wlasciciel REF Wlasciciel2
);
/

CREATE TABLE samochody2 OF Samochod2;

INSERT INTO samochody2 VALUES (Samochod2('ford','mondeo',80000,DATE '1997-05-10',45000,NULL));
INSERT INTO samochody2 VALUES (Samochod2('mazda','323',12000,DATE '2000-09-22',52000,NULL));
INSERT INTO samochody2 VALUES (Samochod2('fiat','brava',60000,DATE '1999-11-30',25000,NULL));

UPDATE samochody2 s
SET s.wlasciciel = (SELECT REF(w) FROM wlasciciele2 w WHERE w.imie='Jan');
-- Zad 6
SET SERVEROUTPUT ON SIZE 30000;

DECLARE
    TYPE t_przedmioty IS VARRAY(10) OF VARCHAR2(20);
    moje_przedmioty t_przedmioty := t_przedmioty('');
BEGIN
    moje_przedmioty(1) := 'MATEMATYKA';
    moje_przedmioty.EXTEND(9);

    FOR i IN 2..10 LOOP
        moje_przedmioty(i) := 'PRZEDMIOT_' || i;
    END LOOP;

    FOR i IN moje_przedmioty.FIRST()..moje_przedmioty.LAST() LOOP
        DBMS_OUTPUT.PUT_LINE(moje_przedmioty(i));
    END LOOP;

    moje_przedmioty.TRIM(2);

    FOR i IN moje_przedmioty.FIRST()..moje_przedmioty.LAST() LOOP
        DBMS_OUTPUT.PUT_LINE(moje_przedmioty(i));
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Limit: ' || moje_przedmioty.LIMIT());
    DBMS_OUTPUT.PUT_LINE('Count: ' || moje_przedmioty.COUNT());

    moje_przedmioty.EXTEND();
    moje_przedmioty(9) := 'PRZEDMIOT_9';

    DBMS_OUTPUT.PUT_LINE('Limit: ' || moje_przedmioty.LIMIT());
    DBMS_OUTPUT.PUT_LINE('Count: ' || moje_przedmioty.COUNT());

    moje_przedmioty.DELETE();

    DBMS_OUTPUT.PUT_LINE('After DELETE - Limit: ' || moje_przedmioty.LIMIT());
    DBMS_OUTPUT.PUT_LINE('After DELETE - Count: ' || moje_przedmioty.COUNT());
END;
/

-- Zad 7
DECLARE
    TYPE t_ksiazki IS VARRAY(5) OF VARCHAR2(50);
    moje_ksiazki t_ksiazki := t_ksiazki('title');
BEGIN
    FOR i IN moje_ksiazki.FIRST()..moje_ksiazki.LAST() LOOP
        DBMS_OUTPUT.PUT_LINE(moje_ksiazki(i));
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Limit: ' || moje_ksiazki.LIMIT());
    DBMS_OUTPUT.PUT_LINE('Count: ' || moje_ksiazki.COUNT());

    moje_ksiazki.EXTEND(4);
    moje_ksiazki(2) := 'Król Szczurów';
    FOR i IN 3..5 LOOP
        moje_ksiazki(i) := 'Book_' || i;
    END LOOP;

    FOR i IN moje_ksiazki.FIRST()..moje_ksiazki.LAST() LOOP
        DBMS_OUTPUT.PUT_LINE(moje_ksiazki(i));
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Limit: ' || moje_ksiazki.LIMIT());
    DBMS_OUTPUT.PUT_LINE('Count: ' || moje_ksiazki.COUNT());

    moje_ksiazki.TRIM(1);
    FOR i IN moje_ksiazki.FIRST()..moje_ksiazki.LAST() LOOP
        DBMS_OUTPUT.PUT_LINE(moje_ksiazki(i));
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Limit: ' || moje_ksiazki.LIMIT());
    DBMS_OUTPUT.PUT_LINE('Count: ' || moje_ksiazki.COUNT());
END;
/

-- Zad 8
DECLARE
    TYPE t_wykladowcy IS TABLE OF VARCHAR2(20);
    moi_wykladowcy t_wykladowcy := t_wykladowcy();
BEGIN
    moi_wykladowcy.EXTEND(2);
    moi_wykladowcy(1) := 'MORZY';
    moi_wykladowcy(2) := 'WOJCIECHOWSKI';
    moi_wykladowcy.EXTEND(8);

    FOR i IN 3..10 LOOP
        moi_wykladowcy(i) := 'WYKLADOWCA_' || i;
    END LOOP;

    FOR i IN moi_wykladowcy.FIRST()..moi_wykladowcy.LAST() LOOP
        DBMS_OUTPUT.PUT_LINE(moi_wykladowcy(i));
    END LOOP;

    moi_wykladowcy.TRIM(2);

    FOR i IN moi_wykladowcy.FIRST()..moi_wykladowcy.LAST() LOOP
        IF moi_wykladowcy.EXISTS(i) THEN
            DBMS_OUTPUT.PUT_LINE(moi_wykladowcy(i));
        END IF;
    END LOOP;

    moi_wykladowcy.DELETE(5,7);

    FOR i IN moi_wykladowcy.FIRST()..moi_wykladowcy.LAST() LOOP
        IF moi_wykladowcy.EXISTS(i) THEN
            DBMS_OUTPUT.PUT_LINE(moi_wykladowcy(i));
        END IF;
    END LOOP;

    moi_wykladowcy(5) := 'ZAKRZEWICZ';
    moi_wykladowcy(6) := 'KROLIKOWSKI';
    moi_wykladowcy(7) := 'KOSZLAJDA';

    FOR i IN moi_wykladowcy.FIRST()..moi_wykladowcy.LAST() LOOP
        IF moi_wykladowcy.EXISTS(i) THEN
            DBMS_OUTPUT.PUT_LINE(moi_wykladowcy(i));
        END IF;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Count: ' || moi_wykladowcy.COUNT());
END;
/

-- Zad 9
DECLARE
    TYPE t_miesiace IS TABLE OF VARCHAR2(20);
    moje_miesiace t_miesiace := t_miesiace();
BEGIN
    moje_miesiace.EXTEND(12);
    moje_miesiace(1) := 'styczen';
    moje_miesiace(2) := 'luty';
    moje_miesiace(3) := 'marzec';
    moje_miesiace(4) := 'kwiecien';
    moje_miesiace(5) := 'maj';
    moje_miesiace(6) := 'czerwiec';
    
    FOR i IN 7..12 LOOP
        moje_miesiace(i) := 'Miesiac_' || i;
    END LOOP;

    FOR i IN moje_miesiace.FIRST()..moje_miesiace.LAST() LOOP
        IF moje_miesiace.EXISTS(i) THEN
            DBMS_OUTPUT.PUT_LINE(moje_miesiace(i));
        END IF;
    END LOOP;

    moje_miesiace.DELETE(7,12);
    moje_miesiace(7) := 'lipiec';

    FOR i IN moje_miesiace.FIRST()..moje_miesiace.LAST() LOOP
        IF moje_miesiace.EXISTS(i) THEN
            DBMS_OUTPUT.PUT_LINE(moje_miesiace(i));
        END IF;
    END LOOP;
END;
/
-- Zad 10
CREATE OR REPLACE TYPE jezyki_obce AS VARRAY(10) OF VARCHAR2(20);
/

CREATE OR REPLACE TYPE stypendium AS OBJECT (
    nazwa VARCHAR2(50),
    kraj VARCHAR2(30),
    jezyki jezyki_obce
);
/

CREATE TABLE stypendia OF stypendium;

INSERT INTO stypendia VALUES ('SOKRATES','FRANCJA',jezyki_obce('ANGIELSKI','FRANCUSKI','NIEMIECKI'));
INSERT INTO stypendia VALUES ('ERASMUS','NIEMCY',jezyki_obce('ANGIELSKI','NIEMIECKI','HISZPANSKI'));
COMMIT;

UPDATE stypendia
SET jezyki = jezyki_obce('ANGIELSKI','NIEMIECKI','HISZPANSKI','FRANCUSKI')
WHERE nazwa = 'ERASMUS';
COMMIT;

-- Zad 10b
CREATE OR REPLACE TYPE lista_egzaminow AS TABLE OF VARCHAR2(20);
/

CREATE OR REPLACE TYPE semestr AS OBJECT (
    numer NUMBER,
    egzaminy lista_egzaminow
);
/

CREATE TABLE semestry OF semestr
NESTED TABLE egzaminy STORE AS tab_egzaminy;

INSERT INTO semestry VALUES (semestr(1,lista_egzaminow('MATEMATYKA','LOGIKA','ALGEBRA')));
INSERT INTO semestry VALUES (semestr(2,lista_egzaminow('BAZY DANYCH','SYSTEMY OPERACYJNE')));
COMMIT;


INSERT INTO TABLE(SELECT s.egzaminy FROM semestry s WHERE numer=2) VALUES('METODY NUMERYCZNE');

UPDATE TABLE(SELECT s.egzaminy FROM semestry s WHERE numer=2) e
SET e.COLUMN_VALUE = 'SYSTEMY ROZPROSZONE'
WHERE e.COLUMN_VALUE = 'SYSTEMY OPERACYJNE';

DELETE FROM TABLE(SELECT s.egzaminy FROM semestry s WHERE numer=2) e
WHERE e.COLUMN_VALUE = 'BAZY DANYCH';
COMMIT;

-- Zad 11
CREATE OR REPLACE TYPE koszyk_produktow AS TABLE OF VARCHAR2(20);
/

CREATE OR REPLACE TYPE zakup AS OBJECT (
    osoba VARCHAR2(50),
    produkty koszyk_produktow
);
/

CREATE TABLE zakupy OF zakup
NESTED TABLE produkty STORE AS tab_produkty;

INSERT INTO zakupy VALUES (zakup('Mateusz Czajka', koszyk_produktow('maslo','chleb','banan')));
INSERT INTO zakupy VALUES (zakup('Jan Kowalski', koszyk_produktow('kowadlo','stal','zelazo')));
INSERT INTO zakupy VALUES (zakup('Antoni Nowak', koszyk_produktow('maslo')));
COMMIT;

DELETE FROM zakupy 
WHERE osoba IN (
    SELECT osoba
    FROM zakupy z, TABLE(z.produkty) p
    WHERE p.COLUMN_VALUE='maslo'
);
COMMIT;

-- Zad 12
CREATE OR REPLACE TYPE instrument AS OBJECT (
    nazwa VARCHAR2(20),
    dzwiek VARCHAR2(20),
    MEMBER FUNCTION graj RETURN VARCHAR2
) NOT FINAL;
/

CREATE OR REPLACE TYPE BODY instrument AS
    MEMBER FUNCTION graj RETURN VARCHAR2 IS
    BEGIN
        RETURN dzwiek;
    END;
END;
/

CREATE OR REPLACE TYPE instrument_dety UNDER instrument (
    material VARCHAR2(20),
    OVERRIDING MEMBER FUNCTION graj RETURN VARCHAR2,
    MEMBER FUNCTION graj(glosnosc VARCHAR2) RETURN VARCHAR2
);
/

CREATE OR REPLACE TYPE BODY instrument_dety AS
    OVERRIDING MEMBER FUNCTION graj RETURN VARCHAR2 IS
    BEGIN
        RETURN 'dmucham: '||dzwiek;
    END;
    MEMBER FUNCTION graj(glosnosc VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN glosnosc||':'||dzwiek;
    END;
END;
/

CREATE OR REPLACE TYPE instrument_klawiszowy UNDER instrument (
    producent VARCHAR2(20),
    OVERRIDING MEMBER FUNCTION graj RETURN VARCHAR2
);
/

CREATE OR REPLACE TYPE BODY instrument_klawiszowy AS
    OVERRIDING MEMBER FUNCTION graj RETURN VARCHAR2 IS
    BEGIN
        RETURN 'stukam w klawisze: '||dzwiek;
    END;
END;
/

DECLARE
    tamburyn instrument := instrument('tamburyn','brzdek-brzdek');
    trabka instrument_dety := instrument_dety('trabka','tra-ta-ta','metalowa');
    fortepian instrument_klawiszowy := instrument_klawiszowy('fortepian','ping-ping','steinway');
BEGIN
    DBMS_OUTPUT.PUT_LINE(tamburyn.graj);
    DBMS_OUTPUT.PUT_LINE(trabka.graj);
    DBMS_OUTPUT.PUT_LINE(trabka.graj('glosno'));
    DBMS_OUTPUT.PUT_LINE(fortepian.graj);
END;
/

-- Zad 13
CREATE OR REPLACE TYPE istota AS OBJECT (
    nazwa VARCHAR2(20),
    NOT INSTANTIABLE MEMBER FUNCTION poluj(ofiara CHAR) RETURN CHAR
) NOT INSTANTIABLE NOT FINAL;
/

CREATE OR REPLACE TYPE lew UNDER istota (
    liczba_nog NUMBER,
    OVERRIDING MEMBER FUNCTION poluj(ofiara CHAR) RETURN CHAR
);
/

CREATE OR REPLACE TYPE BODY lew AS
    OVERRIDING MEMBER FUNCTION poluj(ofiara CHAR) RETURN CHAR IS
    BEGIN
        RETURN 'upolowana ofiara: '||ofiara;
    END;
END;
/

DECLARE
    KrolLew lew := lew('LEW',4);
BEGIN
    DBMS_OUTPUT.PUT_LINE(KrolLew.poluj('antylopa'));
END;
/

-- Zad 15
CREATE TABLE instrumenty OF instrument;

INSERT INTO instrumenty VALUES (instrument('tamburyn','brzdek-brzdek'));
INSERT INTO instrumenty VALUES (instrument_dety('trabka','tra-ta-ta','metalowa'));
INSERT INTO instrumenty VALUES (instrument_klawiszowy('fortepian','ping-ping','steinway'));
COMMIT;

SELECT i.nazwa, i.graj() FROM instrumenty i;

-- Zad 16
CREATE TABLE PRZEDMIOTY (
    NAZWA VARCHAR2(50),
    NAUCZYCIEL NUMBER REFERENCES PRACOWNICY(ID_PRAC)
);

INSERT INTO PRZEDMIOTY VALUES ('BAZY DANYCH',100);
INSERT INTO PRZEDMIOTY VALUES ('SYSTEMY OPERACYJNE',100);
INSERT INTO PRZEDMIOTY VALUES ('PROGRAMOWANIE',110);
INSERT INTO PRZEDMIOTY VALUES ('SIECI KOMPUTEROWE',110);
INSERT INTO PRZEDMIOTY VALUES ('BADANIA OPERACYJNE',120);
INSERT INTO PRZEDMIOTY VALUES ('GRAFIKA KOMPUTEROWA',120);
INSERT INTO PRZEDMIOTY VALUES ('BAZY DANYCH',130);
INSERT INTO PRZEDMIOTY VALUES ('SYSTEMY OPERACYJNE',140);
INSERT INTO PRZEDMIOTY VALUES ('PROGRAMOWANIE',140);
INSERT INTO PRZEDMIOTY VALUES ('SIECI KOMPUTEROWE',140);
INSERT INTO PRZEDMIOTY VALUES ('BADANIA OPERACYJNE',150);
INSERT INTO PRZEDMIOTY VALUES ('GRAFIKA KOMPUTEROWA',150);
INSERT INTO PRZEDMIOTY VALUES ('BAZY DANYCH',160);
INSERT INTO PRZEDMIOTY VALUES ('SYSTEMY OPERACYJNE',160);
INSERT INTO PRZEDMIOTY VALUES ('PROGRAMOWANIE',170);
INSERT INTO PRZEDMIOTY VALUES ('SIECI KOMPUTEROWE',180);
INSERT INTO PRZEDMIOTY VALUES ('BADANIA OPERACYJNE',180);
INSERT INTO PRZEDMIOTY VALUES ('GRAFIKA KOMPUTEROWA',190);
INSERT INTO PRZEDMIOTY VALUES ('GRAFIKA KOMPUTEROWA',200);
INSERT INTO PRZEDMIOTY VALUES ('GRAFIKA KOMPUTEROWA',210);
INSERT INTO PRZEDMIOTY VALUES ('PROGRAMOWANIE',220);
INSERT INTO PRZEDMIOTY VALUES ('SIECI KOMPUTEROWE',220);
INSERT INTO PRZEDMIOTY VALUES ('BADANIA OPERACYJNE',230);
COMMIT;

-- Zad 17
CREATE OR REPLACE TYPE ZESPOL AS OBJECT (
    ID_ZESP NUMBER,
    NAZWA VARCHAR2(50),
    ADRES VARCHAR2(100)
);
/

-- Zad 18
CREATE OR REPLACE VIEW ZESPOLY_V OF ZESPOL
WITH OBJECT IDENTIFIER(ID_ZESP)
AS SELECT ID_ZESP, NAZWA, ADRES FROM ZESPOLY;
/

-- Zad 19
CREATE OR REPLACE TYPE PRZEDMIOTY_TAB AS TABLE OF VARCHAR2(100);
/

CREATE OR REPLACE TYPE PRACOWNIK AS OBJECT (
    ID_PRAC NUMBER,
    NAZWISKO VARCHAR2(30),
    ETAT VARCHAR2(20),
    ZATRUDNIONY DATE,
    PLACA_POD NUMBER(10,2),
    MIEJSCE_PRACY REF ZESPOL,
    PRZEDMIOTY PRZEDMIOTY_TAB,
    MEMBER FUNCTION ILE_PRZEDMIOTOW RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY PRACOWNIK AS
    MEMBER FUNCTION ILE_PRZEDMIOTOW RETURN NUMBER IS
    BEGIN
        RETURN PRZEDMIOTY.COUNT();
    END ILE_PRZEDMIOTOW;
END;
/

-- Zad 20
CREATE OR REPLACE VIEW PRACOWNICY_V OF PRACOWNIK
WITH OBJECT IDENTIFIER(ID_PRAC)
AS 
SELECT 
    P.ID_PRAC, 
    P.NAZWISKO, 
    P.ETAT, 
    P.ZATRUDNIONY, 
    P.PLACA_POD,
    MAKE_REF(ZESPOLY_V, ID_ZESP),
    CAST(MULTISET(
        SELECT NAZWA FROM PRZEDMIOTY WHERE NAUCZYCIEL=P.ID_PRAC
    ) AS PRZEDMIOTY_TAB)
FROM PRACOWNICY P;
/

-- Zad 21
SELECT * FROM PRACOWNICY_V;
SELECT P.NAZWISKO, P.ETAT, P.MIEJSCE_PRACY.NAZWA FROM PRACOWNICY_V P;
SELECT P.NAZWISKO, P.ILE_PRZEDMIOTOW() FROM PRACOWNICY_V P;
SELECT * FROM TABLE(SELECT PRZEDMIOTY FROM PRACOWNICY_V WHERE NAZWISKO='WEGLARZ');

-- Zad 22
CREATE TABLE PISARZE (
    ID_PISARZA NUMBER PRIMARY KEY,
    NAZWISKO VARCHAR2(20),
    DATA_UR DATE
);

CREATE TABLE KSIAZKI (
    ID_KSIAZKI NUMBER PRIMARY KEY,
    ID_PISARZA NUMBER REFERENCES PISARZE,
    TYTUL VARCHAR2(50),
    DATA_WYDANIE DATE
);

INSERT INTO PISARZE VALUES(10,'SIENKIEWICZ',DATE '1880-01-01');
INSERT INTO PISARZE VALUES(20,'PRUS',DATE '1890-04-12');
INSERT INTO PISARZE VALUES(30,'ZEROMSKI',DATE '1899-09-11');

INSERT INTO KSIAZKI VALUES(10,10,'OGNIEM I MIECZEM',DATE '1990-01-05');
INSERT INTO KSIAZKI VALUES(20,10,'POTOP',DATE '1975-12-09');
INSERT INTO KSIAZKI VALUES(30,10,'PAN WOLODYJOWSKI',DATE '1987-02-15');
INSERT INTO KSIAZKI VALUES(40,20,'FARAON',DATE '1948-01-21');
INSERT INTO KSIAZKI VALUES(50,20,'LALKA',DATE '1994-08-01');
INSERT INTO KSIAZKI VALUES(60,30,'PRZEDWIOSNIE',DATE '1938-02-02');
COMMIT;

CREATE OR REPLACE TYPE ksiazki_tab AS TABLE OF VARCHAR2(50);
/

CREATE OR REPLACE TYPE pisarz AS OBJECT (
    ID_PISARZA NUMBER,
    NAZWISKO VARCHAR2(20),
    DATA_UR DATE,
    KSIAZKI ksiazki_tab,
    MEMBER FUNCTION liczba_ksiazek RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY pisarz AS
    MEMBER FUNCTION liczba_ksiazek RETURN NUMBER IS
    BEGIN
        RETURN KSIAZKI.COUNT();
    END;
END;
/

CREATE OR REPLACE TYPE ksiazka AS OBJECT (
    ID_KSIAZKI NUMBER,
    autor REF pisarz,
    TYTUL VARCHAR2(50),
    DATA_WYDANIE DATE,
    MEMBER FUNCTION wiek RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY ksiazka AS
    MEMBER FUNCTION wiek RETURN NUMBER IS
    BEGIN
        RETURN EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATA_WYDANIE);
    END;
END;
/

-- Views
CREATE OR REPLACE VIEW pisarze_widok OF pisarz
WITH OBJECT IDENTIFIER(ID_PISARZA)
AS SELECT 
    p.ID_PISARZA, 
    p.NAZWISKO, 
    p.DATA_UR, 
    CAST(MULTISET(
        SELECT tytul FROM ksiazki WHERE id_pisarza=p.id_pisarza
    ) AS ksiazki_tab)
FROM pisarze p;
/

CREATE OR REPLACE VIEW ksiazki_widok OF ksiazka
WITH OBJECT IDENTIFIER(ID_KSIAZKI)
AS SELECT
    k.ID_KSIAZKI,
    MAKE_REF(pisarze_widok, k.ID_PISARZA),
    k.TYTUL,
    k.DATA_WYDANIE
FROM ksiazki k;
/

SELECT k.TYTUL, k.DATA_WYDANIE, k.autor, k.wiek() FROM ksiazki_widok k;
SELECT * FROM pisarze_widok;

-- Zad 23
CREATE OR REPLACE TYPE AUTO AS OBJECT (
    MARKA VARCHAR2(20),
    MODEL VARCHAR2(20),
    KILOMETRY NUMBER,
    DATA_PRODUKCJI DATE,
    CENA NUMBER(10,2),
    MEMBER FUNCTION WARTOSC RETURN NUMBER
) NOT FINAL;
/

CREATE OR REPLACE TYPE BODY AUTO AS
    MEMBER FUNCTION WARTOSC RETURN NUMBER IS
        WIEK NUMBER;
        WARTOSC NUMBER;
    BEGIN
        WIEK := ROUND(MONTHS_BETWEEN(SYSDATE,DATA_PRODUKCJI)/12);
        WARTOSC := CENA - (WIEK * 0.1 * CENA);
        IF WARTOSC < 0 THEN
            WARTOSC := 0;
        END IF;
        RETURN WARTOSC;
    END WARTOSC;
END;
/

CREATE OR REPLACE TYPE auto_osobowe UNDER auto (
    liczba_miejsc NUMBER,
    klimatyzacja NUMBER(1),
    OVERRIDING MEMBER FUNCTION WARTOSC RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY auto_osobowe AS
    OVERRIDING MEMBER FUNCTION WARTOSC RETURN NUMBER IS
        wartosc NUMBER;
    BEGIN
        wartosc := (SELF AS auto).wartosc();
        IF klimatyzacja > 0 THEN
            wartosc := wartosc * 1.5;
        END IF;
        RETURN wartosc;
    END;
END;
/

CREATE OR REPLACE TYPE auto_ciezarowe UNDER auto (
    max_ladownosc NUMBER,
    OVERRIDING MEMBER FUNCTION WARTOSC RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY auto_ciezarowe AS
    OVERRIDING MEMBER FUNCTION WARTOSC RETURN NUMBER IS
        wartosc NUMBER;
    BEGIN
        wartosc := (SELF AS auto).wartosc();
        IF max_ladownosc > 10000 THEN
            wartosc := wartosc * 2;
        END IF;
        RETURN wartosc;
    END;
END;
/

CREATE TABLE AUTA OF AUTO;

INSERT INTO AUTA VALUES (AUTO('FIAT','BRAVA',60000,DATE '1999-11-30',25000));
INSERT INTO AUTA VALUES (AUTO('FORD','MONDEO',80000,DATE '1997-05-10',45000));
INSERT INTO AUTA VALUES (AUTO('MAZDA','323',12000,DATE '2000-09-22',52000));
INSERT INTO AUTA VALUES (auto_osobowe('marka1','model1',1000,DATE '2020-02-02',2000,4,1));
INSERT INTO AUTA VALUES (auto_osobowe('marka2','model2',1000,DATE '2020-02-02',2000,4,0));
INSERT INTO AUTA VALUES (auto_ciezarowe('marka3','model3',1000,DATE '2020-02-02',2000,10000));
INSERT INTO AUTA VALUES (auto_ciezarowe('marka4','model4',1000,DATE '2020-02-02',2000,20000));
COMMIT;

SELECT a.MARKA, a.MODEL, a.WARTOSC() FROM AUTA a;
