-- Zadanie 1 A
select lpad('-', 2*(level-1),'-') || t.owner||'.'||t.type_name||' (FINAL:'||t.final||
', INSTANTIABLE:'||t.instantiable||', ATTRIBUTES:'||t.attributes||', METHODS:'||t.methods||')'
from all_types t
start with t.type_name = 'ST_GEOMETRY'
connect by prior t.type_name = t.supertype_name
and prior t.owner = t.owner;

-- Zadanie 1 B
select distinct m.method_name
from all_type_methods m
where m.type_name like 'ST_POLYGON'
and m.owner = 'MDSYS'
order by 1;

-- Zadanie 1 C
create table MYST_MAJOR_CITIES (
    FIPS_CNTRY VARCHAR2(2),
    CITY_NAME VARCHAR2(40),
    STGEOM MDSYS.ST_POINT
);

-- Zadanie 1 D
INSERT INTO MYST_MAJOR_CITIES
SELECT FIPS_CNTRY, CITY_NAME, MDSYS.ST_POINT(GEOM)
FROM MAJOR_CITIES;

-- Zadanie 2 A
INSERT INTO MYST_MAJOR_CITIES VALUES (
    'PL', 
    'Szczyrk', 
    MDSYS.ST_POINT(19.036107, 49.718655, 8307)
);

-- Zadanie 3 A
create table MYST_COUNTRY_BOUNDARIES (
    FIPS_CNTRY VARCHAR2(2),
    CNTRY_NAME VARCHAR2(40),
    STGEOM MDSYS.ST_MULTIPOLYGON
);

-- Zadanie 3 B
INSERT INTO MYST_COUNTRY_BOUNDARIES
SELECT FIPS_CNTRY, CNTRY_NAME, MDSYS.ST_MULTIPOLYGON(GEOM)
FROM COUNTRY_BOUNDARIES;

-- Zadanie 3 C
SELECT B.STGEOM.ST_GEOMETRYTYPE() as TYP_OBIEKTU, COUNT(*) as ILE
FROM MYST_COUNTRY_BOUNDARIES B
GROUP BY B.STGEOM.ST_GEOMETRYTYPE();

-- Zadanie 3 D
SELECT B.STGEOM.ST_ISSIMPLE()
FROM MYST_COUNTRY_BOUNDARIES B;

-- Zadanie 4 A
SELECT B.CNTRY_NAME, COUNT(*)
FROM MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
WHERE C.STGEOM.ST_WITHIN(B.STGEOM) = 1
GROUP BY B.CNTRY_NAME;

-- Zadanie 4 B
SELECT A.CNTRY_NAME A_NAME, B.CNTRY_NAME B_NAME
FROM MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
WHERE A.CNTRY_NAME = 'Czech Republic'
AND B.STGEOM.ST_TOUCHES(A.STGEOM) = 1;

-- Zadanie 4 C
SELECT DISTINCT B.CNTRY_NAME, R.NAME
FROM MYST_COUNTRY_BOUNDARIES B, RIVERS R
WHERE B.CNTRY_NAME = 'Czech Republic'
AND MDSYS.ST_LINESTRING(R.GEOM).ST_INTERSECTS(B.STGEOM) = 1;

-- Zadanie 4 D
SELECT TREAT(A.STGEOM.ST_UNION(B.STGEOM) as ST_POLYGON).ST_AREA() POWIERZCHNIA
FROM MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
WHERE A.CNTRY_NAME = 'Czech Republic'
AND B.CNTRY_NAME = 'Slovakia';

-- Zadanie 4 E
SELECT B.STGEOM.ST_DIFFERENCE(MDSYS.ST_GEOMETRY(W.GEOM)).ST_GEOMETRYTYPE() WEGRY_BEZ
FROM MYST_COUNTRY_BOUNDARIES B, WATER_BODIES W
WHERE B.CNTRY_NAME = 'Hungary'
AND W.NAME = 'Balaton';

-- Zadanie 5 A
EXPLAIN PLAN FOR
SELECT B.CNTRY_NAME A_NAME, COUNT(*)
FROM MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
WHERE SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE'
AND B.CNTRY_NAME = 'Poland'
GROUP BY B.CNTRY_NAME;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Zadanie 5 B
INSERT INTO USER_SDO_GEOM_METADATA
SELECT 'MYST_MAJOR_CITIES', 'STGEOM', T.DIMINFO, T.SRID
FROM ALL_SDO_GEOM_METADATA T
WHERE T.TABLE_NAME = 'MAJOR_CITIES';

INSERT INTO USER_SDO_GEOM_METADATA
SELECT 'MYST_COUNTRY_BOUNDARIES', 'STGEOM', T.DIMINFO, T.SRID
FROM ALL_SDO_GEOM_METADATA T
WHERE T.TABLE_NAME = 'COUNTRY_BOUNDARIES';

-- Zadanie 5 C
CREATE INDEX MYST_MAJOR_CITIES_IDX ON MYST_MAJOR_CITIES(STGEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX MYST_COUNTRY_BOUNDARIES_IDX ON MYST_COUNTRY_BOUNDARIES(STGEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- Zadanie 5 D
EXPLAIN PLAN FOR
SELECT B.CNTRY_NAME A_NAME, COUNT(*)
FROM MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
WHERE SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE'
AND B.CNTRY_NAME = 'Poland'
GROUP BY B.CNTRY_NAME;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);