(:for $k in doc('file:///D:/Dokumenty/Studia/TPD/Semestr2/ZTPD/lab8/XPath-XSLT/XPath-XSLT/swiat.xml')//KRAJ:)
(:where substring($k/NAZWA, 1, 1) = substring($k/STOLICA, 1, 1):)
(:return <KRAJ>:)
(: {$k/NAZWA, $k/STOLICA}:)
(:</KRAJ>:)

(:32:)
(:doc('file:///D:/Dokumenty/Studia/TPD/Semestr2/ZTPD/lab8/XPath-XSLT/XPath-XSLT/zesp_prac.xml')//NAZWISKO:)
(:33:)
(:doc('file:///D:/Dokumenty/Studia/TPD/Semestr2/ZTPD/lab8/XPath-XSLT/XPath-XSLT/zesp_prac.xml')/ZESPOLY/ROW[NAZWA='SYSTEMY EKSPERCKIE']/PRACOWNICY/ROW/NAZWISKO:)
(:34:)
(:count(doc('file:///D:/Dokumenty/Studia/TPD/Semestr2/ZTPD/lab8/XPath-XSLT/XPath-XSLT/zesp_prac.xml')/ZESPOLY/ROW[ID_ZESP=10]/PRACOWNICY/ROW):)
(:35:)
(:doc('file:///D:/Dokumenty/Studia/TPD/Semestr2/ZTPD/lab8/XPath-XSLT/XPath-XSLT/zesp_prac.xml')//PRACOWNICY/ROW[ID_SZEFA=100]/NAZWISKO:)
(:36:)
sum(doc('file:///D:/Dokumenty/Studia/TPD/Semestr2/ZTPD/lab8/XPath-XSLT/XPath-XSLT/zesp_prac.xml')/ZESPOLY/ROW[PRACOWNICY/ROW/NAZWISKO='BRZEZINSKI']/PRACOWNICY/ROW/PLACA_POD)