-- Zadanie 1.A
CREATE TABLE S6_LRS (
    GEOM MDSYS.SDO_GEOMETRY
);

-- Zadanie 1.B
INSERT INTO S6_LRS
SELECT SR.GEOM
FROM STREETS_AND_RAILROADS SR, MAJOR_CITIES C
WHERE C.CITY_NAME = 'Koszalin'
  AND SDO_RELATE(SR.GEOM,
        SDO_GEOM.SDO_BUFFER(C.GEOM, 10, 1, 'unit=km'),
        'MASK=ANYINTERACT') = 'TRUE';

-- Zadanie 1.C
SELECT 
    SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km') AS DISTANCE,
    ST_LINESTRING(GEOM).ST_NUMPOINTS() AS ST_NUMPOINTS
FROM S6_LRS;

-- Zadanie 1.D
UPDATE S6_LRS
SET GEOM = SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, 276.6813154);

-- Zadanie 1.E
INSERT INTO USER_SDO_GEOM_METADATA
VALUES (
    'S6_LRS',
    'GEOM',
    MDSYS.SDO_DIM_ARRAY(
        MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
        MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
        MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1)
    ),
    8307
);

-- Zadanie 1.F: Utwórz indeks przestrzenny na tabeli S6_LRS.
CREATE INDEX lrs_s6_idx ON S6_LRS(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- Zadanie 2.A
SELECT SDO_LRS.VALID_MEASURE(GEOM, 500) AS VALID_500
FROM S6_LRS;

-- Zadanie 2.B
SELECT SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) AS END_PT
FROM S6_LRS;

-- Zadanie 2.C
SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0) AS KM150
FROM S6_LRS;

-- Zadanie 2.D
SELECT SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) AS CLIPPED
FROM S6_LRS;

-- Zadanie 2.E
SELECT SDO_LRS.PROJECT_PT(S6.GEOM, C.GEOM) AS WJAZD_NA_S6
FROM S6_LRS S6, MAJOR_CITIES C
WHERE C.CITY_NAME = 'Slupsk';

-- Zadanie 2.F
SELECT SDO_GEOM.SDO_LENGTH(
    SDO_LRS.OFFSET_GEOM_SEGMENT(S6.GEOM, M.DIMINFO, 50, 200, 50, 'unit=m'), 
    1, 'unit=km') AS KOSZT
FROM S6_LRS S6, USER_SDO_GEOM_METADATA M
WHERE M.TABLE_NAME = 'S6_LRS' AND M.COLUMN_NAME = 'GEOM';